import 'package:freezed_annotation/freezed_annotation.dart';

part 'login_request_body.g.dart';

@JsonSerializable()
class LoginRequestBody {
  final String email;
  final String password;

  LoginRequestBody({required this.email, required this.password});

  Map<String, dynamic> toJson() => _$LoginRequestBodyToJson(this);
}

// i will send the email and password via this request body, so i will use toJson (عشان احول كود ال دارت اللى انا هبعته ل جيسون)
// _$LoginRequestBodyToJson(this); << to make an autogenerated file
